# Generated by Django 6.0.4 on 2026-05-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(choices=[('netflix', 'Netflix'), ('prime', 'Amazon Prime Video'), ('jio', 'JioCinema'), ('hotstar', 'Disney+ Hotstar'), ('apple', 'Apple TV+'), ('zee5', 'ZEE5'), ('sonyliv', 'SonyLIV'), ('other', 'Other')], max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='platforms/')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('original_title', models.CharField(blank=True, max_length=500)),
                ('overview', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show')], db_index=True, default='movie', max_length=10)),
                ('release_date', models.DateField(blank=True, db_index=True, null=True)),
                ('release_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('runtime', models.IntegerField(blank=True, help_text='Minutes', null=True)),
                ('vote_average', models.FloatField(db_index=True, default=0.0)),
                ('vote_count', models.IntegerField(default=0)),
                ('popularity', models.FloatField(db_index=True, default=0.0)),
                ('poster_path', models.CharField(blank=True, max_length=500)),
                ('backdrop_path', models.CharField(blank=True, max_length=500)),
                ('original_language', models.CharField(blank=True, db_index=True, max_length=10)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('adult', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies.genre')),
                ('platforms', models.ManyToManyField(blank=True, related_name='movies', to='movies.platform')),
            ],
            options={
                'ordering': ['-popularity'],
                'indexes': [models.Index(fields=['release_year', 'vote_average'], name='movies_movi_release_468486_idx'), models.Index(fields=['content_type', 'release_year'], name='movies_movi_content_5247f3_idx'), models.Index(fields=['popularity'], name='movies_movi_popular_114287_idx')],
            },
        ),
    ]
