# Generated by Django 6.0.4 on 2026-05-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_youtube_key',
            field=models.CharField(blank=True, help_text='YouTube video ID e.g. dQw4w9WgXcQ', max_length=50),
        ),
    ]
