# Generated by Django 6.0.4 on 2026-05-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_trailer_youtube_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(blank=True, help_text='Comma separated actor names — e.g. Tom Hanks, Brad Pitt, Leonardo DiCaprio'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, help_text='Director name(s)', max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_youtube_key',
            field=models.CharField(blank=True, help_text='YouTube video ID — e.g. dQw4w9WgXcQ (from youtube.com/watch?v=THIS_PART)', max_length=50),
        ),
    ]
