# Generated by Django 6.0.4 on 2026-06-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_cast_movie_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='platforms_checked',
            field=models.BooleanField(db_index=True, default=False, help_text='True after JustWatch availability has been fetched for this title'),
        ),
    ]
